spring.application.name=demo1


#Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/test_database
spring.datasource.username=postgres
spring.datasource.password=postgres



#JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true